# Generated by Django 5.0.7 on 2024-11-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rollno', models.IntegerField()),
                ('city', models.CharField(max_length=150)),
            ],
        ),
    ]
